<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bfbnnews"
 *
 * Auto generated by Extension Builder 2021-02-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BFBN News',
    'description' => 'Erweiterung der Extension News um Felder für Termin',
    'category' => 'plugin',
    'author' => 'BFBN-Team',
    'author_email' => 'mbsued.ma4@augsburg.de',
    'state' => 'stable',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.0.0-11.99.99',
			'news' => '9.0.0-10.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
